### ISSUE TITLE
Auth fails when using sample configuration options

### ISSUE THREAD

**Issue by reduxdj** [kahmali/meteor-restivus#114]
This is probably user error, but I can never get to my resource. Seems like some of the documentation is inconsistent, or i just simply can't make it work from your example.
```
if Meteor.isServer
  @Api = new Restivus(
    apiPath: 'api/'
    auth:
      token: 'auth.apiKey'
      user: ->
        userId: @request.headers['x-user-Id']
        token: @request.headers['X-auth-token']

    defaultHeaders:
      'Content-Type': 'application/json'
    onLoggedIn: -> console.log "#{@user.username} (#{@userId}) logged in"
    onLoggedOut: -> console.log "#{@user.username} (#{@userId}) logged out"
    prettyJson: true
    useDefaultAuth: true
    version: 'v1'
  )

```

```

$ curl http://local.nmarket.me:8888/api/v1/login -d "password=password&user=reduxdj"
{
  "status": "success",
  "data": {
    "authToken": "jYZSQTYkYgHmy8I_6ThiyzkDygBP8kNRahgCnFU7O7O",
    "userId": "hPfAhEBGp6igrgFAX"
  }
}

$ curl -H  "X-Auth-Token: jYZSQTYkYgHmy8I_6ThiyzkDygBP8kNRahgCnFU7O7O" -H "X-User-Id: "hPfAhEBGp6igrgFAX  -X GET http://local.nmarket.me:8888/api/v1/user
{
  "status": "error",
  "message": "You must be logged in to do this."
}
```
